# See https://developer.github.com/v3/repos/#edit for all available settings.
repository:
  name: ussf-portal-prototype
  description: Prototype of the USSF portal for testing purposes
  homepage: https://prototype.ussforbit.us/
  private: false
  has_issues: true
  has_projects: true
  has_wiki: true
  default_branch: main
  allow_squash_merge: true
  # This will allow merge commits on branches, but only squash merges allowed on main (below)
  allow_merge_commit: true
  allow_rebase_merge: true
  delete_branch_on_merge: true
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true

# Labels: define labels for Issues and Pull Requests
labels:
  - name: bug
    color: CC0000
  - name: feature
    color: 336699
  - name: first-timers-only
    # include the old name to rename and existing label
    oldname: Help Wanted

branches:
  - name: main
    # Branch Protection settings. Set to null to disable
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        dismissal_restrictions:
          users: []
          teams: []
      # Required. Require status checks to pass before merging. Set to null to disable
      required_status_checks:
        # Required. Require branches to be up to date before merging.
        strict: true
        # Required. The list of status checks to require in order to merge into this branch
        contexts: []
      # Required. Enforce all configured restrictions for administrators. Set to true to enforce required status checks for repository administrators. Set to null to disable.
      enforce_admins: true
      # Commits pushed to matching branches must have verified signatures. Set to false to disable.
      required_signatures: true
      required_linear_history: true
      allow_force_pushes: false
      allow_deletions: false
      # Required. Restrict who can push to this branch. Team and user restrictions are only available for organization-owned repositories. Set to null to disable.
      restrictions:
        apps: []
        users: []
        teams: []
