# See https://developer.github.com/v3/repos/#edit for all available settings.
repository:
  name: ussf-portal-prototype
  description: Prototype of the USSF portal for testing purposes
  homepage: https://prototype.ussforbit.us/
  private: false
  has_issues: true
  has_projects: true
  has_wiki: true
  default_branch: main
  allow_squash_merge: true
  # This will allow merge commits on branches, but only squash merges allowed on main (below)
  allow_merge_commit: true
  allow_rebase_merge: true
  delete_branch_on_merge: true
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true

# Labels: define labels for Issues and Pull Requests
labels:
  - name: help
    color: '#5a87f9'
    description: 'extra attention is needed'
  - name: question
    color: '#ff00ff'
    description: 'further information is requested'
  - name: schedule meeting
    color: '#980000'
    description: 'find time to chat w/ some folks'
  - name: infrastructure
    color: '#9900ff'
    description: 'for issues requiring infra artifacts and or support'
  - name: design
    color: '#f9cb9c'
    description: 'for issues requiring design artifacts and or support'
  - name: prototype
    color: '#00ffff'
    description: 'for all hardware / software issues impacting the prototype' 
  - name: dependencies
    color: '#cfe2f3'
  - name: MVP
    color: '#c27ba0'
    description: 'issues pertaining to MVP feature set (e.g. search or personalization MVP)'
  - name: mobile
    color: '#45818e'
  - name: good first issue
    color: '#351c75'
    description: 'good for newcomers'
  - name: 'severity: 1'
    color: '#ff4c4c'
    description: 'critical/blocker bug, nothing works or major outtage'
  - name: 'severity: 2'
    color: '#ff7f7f'
    description: 'major bug, core feature(s) not working as intended with no workaround'
  - name: 'severity: 3'
    color: '#ffb2b2'
    description: 'minor bug, some unexpected/undesired behavior but workarounds exist'
  - name: 'severity: 4'
    color: '#ffe5e5'
    description: 'low bug, cosmetic, does not disrupt any functionality'
  - name: 'priority: core functionality'
    color: '#ffa500'
    description: 'issues core to feature goal/outcome'
  - name: 'priority: nice to have'
    color: '#ffb732'
    description: 'issues that are enhancement or non-MVP'
  - name: 'priority: critical'
    color: '#ffc966'
  - name: 'priority: high'
    color: '#ffdb99'
    description: 'issues that must be implemented'
  - name: 'priority: medium'
    color: '#ffedcc'
    description: 'issues that should be implemented'
  - name: 'priority: low'
    color: '#fff6e5'
    description: 'issues that could be implemented'
  - name: 'type: bug'
    color: '#ff4c4c'
    description: 'something is not working as intended. used in tandem with severity 1-4'
  - name: 'type: chore'
    color: '#ff7f7f'
    description: 'non-code changing tasks'
  - name: 'type: spike'
    color: '#ffb2b2'
    description: 'research tasks'
  - name: 'type: discussion'
    color: '#ffe5e5'
  - name: 'type: documentation'
    color: '#ffa500'
    description: 'we need to write stuff down somewhere'
  - name: 'type: feature'
    color: '#ffb732'
    description: 'piece of desired functionality'
  - name: 'type: security / ATO'
    color: '#ffc966'
    description: 'all things related to security or required for an ATO'
  - name: 'type: enhancement'
    color: '#ffdb99'
    description: 'updates to current features'
  - name: 'type: maintenance'
    color: '#ffedcc'
  - name: 'type: tech debt'
    color: '#fff6e5'
  - name: 'type: task'
    color: '#674ea7'
  - name: 'type: regression'
    color: '#bf9000'
    description: 'something new broke something old'
  - name: 'type: test coverage'
    color: '#6aa84f'
    description: 'tests needed somewhere'
  - name: 'type: a11y'
    color: '#f1c232'
    description: 'issues covering accessibility implementation'
  - name: 'type: storybook component'
    color: '#660000'
    description: 'issues covering the creation of new components or updates to existing components in storybook'
  - name: 'type: design assets'
    color: '#efefef'
    description: 'issues where particular design assets are required as part of the AC'
  - name: 'type: ci/cd'
    description: 'changes that affect the build/deploy pipeline'
    color: '#666666'
  - name: 'type: breaking'
    color: '#c305d9'
  - name: 'type: dependencies'
    color: '#6ae2da'
  - name: 'type: refactor'
    color: '#7e709c'
  - name: 'type: release'
    color: '#97dbed'
  - name: 'status: on hold'
    color: '#0000ff'
    description: 'work on pause pending some other external force'
  - name: 'status: waiting on others'
    color: '#3232ff'
    description: 'requires work or feedback from others before resuming work'
  - name: 'status: abandoned'
    color: '#6666ff'
    description: 'issue no longer a requirement'
  - name: 'status: duplicate'
    color: '#9999ff'
    description: 'issue already exists'
  - name: 'status: stale'
    color: '#ccccff'
    description: 'issue has been in the backlog for too long and needs a fresh pair of eyes'
  - name: 'status: WIP'
    color: '#7f7fff'
    description: 'requirements still being gathered'
  - name: 'status: wontfix'
    color: '#e5e5ff'
    description: 'noted but will not resolve the issue for various reasons'
  - name: 'topic: cms'
    color: '#008000'
    description: 'all things CMS and its impact on the project'
  - name: 'topic: analytics'
    color: '#329932'
    description: 'all things analytics and its impact on the project'
  - name: 'topic: testing'
    color: '#66b266'
    description: 'tooling and coverage discussions for automated testing'
  - name: 'topic: UX'
    color: '#99cc99'
  - name: 'topic: NextJS'
    color: '#cce5cc'
  - name: 'topic: React'
    color: '#2f972f'
  - name: 'topic: a11y'
    color: '#5eae5e'
    description: 'all things accesibility and its impact on the project'
  - name: 'topic: storybook'
    color: '#8cc58c'
  - name: 'topic: migration'
    color: '#badcba'
  - name: 'needs: research'
    color: '#ffff00'
    description: 'issues requiring more research before starting'
  - name: 'needs: feedback'
    color: '#ffff4c'
    description: 'issues that are looking for feedback from folks before starting'
  - name: 'needs: approval'
    color: '#ffff7f'
    description: 'issues that need sign-off before moving forward'
  - name: 'needs: design'
    color: '#ffffb2'
    description: 'issues that need more design assets'
  - name: 'needs: refinement'
    color: '#ffffe5'
    description: 'issues that need to be broken down further'

branches:
  - name: main
    # Branch Protection settings. Set to null to disable
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        dismissal_restrictions:
          users: []
          teams: []
      # Required. Require status checks to pass before merging. Set to null to disable
      required_status_checks:
        # Required. Require branches to be up to date before merging.
        strict: true
        # Required. The list of status checks to require in order to merge into this branch
        contexts: []
      # Required. Enforce all configured restrictions for administrators. Set to true to enforce required status checks for repository administrators. Set to null to disable.
      enforce_admins: true
      # Commits pushed to matching branches must have verified signatures. Set to false to disable.
      required_signatures: true
      required_linear_history: true
      allow_force_pushes: false
      allow_deletions: false
      # Required. Restrict who can push to this branch. Team and user restrictions are only available for organization-owned repositories. Set to null to disable.
      restrictions:
        apps: []
        users: []
        teams: []
