name: JFrog CLI

#on: [push]
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Artifactory
        uses: katcosgrove/jfrogcli-action@master
        with:
            cmd: 'ping'
        env:
            auth: ${{ secrets.ART_AUTH }}
            accesstoken: ${{ secrets.ART_ACCESSTOKEN }}
            url: ${{ secrets.ART_URL }}