name: Lint PR

on:
  pull_request_target:
    types: [opened, edited, synchronize]
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Lint pr title
        uses: amannn/action-semantic-pull-request@64af21fcd40adf9128bc9fd99b2d566437682b07 # renovate: tag=v3.4.4
        with:
          wip: true
          types: |
            build
            chore
            ci
            feat
            fix
            docs
            style
            refactor
            perf
            test
            component

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
