name: Lint PR

on:
  pull_request_target:
    types: [opened, edited, synchronize]
    branches:
      - main
      - 20-github-semantic-pr
      - test-branch

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Lint pr title
        uses: amannn/action-semantic-pull-request@v3.4.0
        with:
          validateSingleCommit: true
          wip: true
          types:
            - build
            - chore
            - ci
            - feat
            - fix
            - docs
            - style
            - refactor
            - perf
            - test
            - component

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
