name: Lint PR

on:
  pull_request_target:
    types: [opened, edited, synchronize]
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Lint pr title
        uses: amannn/action-semantic-pull-request@v3.4.0
        with:
          validateSingleCommit: true
          wip: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
