name: Lint PR

on:
  pull_request_target:
    types: [opened, edited, synchronize]
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Lint pr title
        uses: amannn/action-semantic-pull-request@536f681e2c60d973396eb60457d42ced8cd3f61a # renovate: tag=v3.7.0
        with:
          wip: true
          types: |
            build
            chore
            ci
            feat
            fix
            docs
            style
            refactor
            perf
            test
            component

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
