name: Testing Github Actions Things.

on:
  pull_request:
    branches: [main]

jobs:
  get-things:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get tag
      run: |
        echo "SHORT_SHA=`echo ${GITHUB_SHA} |cut -c1-8`" >> $GITHUB_ENV
        echo $SHORT_SHA
        echo github.event.pull_request_number = ${{ github.event.pull_request_number }}
