name: Testing Github Actions Things.

on:
  pull_request:
    branches: [main]

jobs:
  build-and-push-aws:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
    - name: Get tag
      run: |
        echo git.short.sha = ${{ github.sha:7 }}
        echo github.event.pull_request_number = ${{ github.event.pull_request_number }}
