name: Testing Github Actions Things.

on:
  pull_request:
    branches: [main]

jobs:
  build-and-push-aws:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@7884fcad6b5d53d10323aee724dc68d8b9096a2e # tag=v2
    - name: Get tag
      run: |
        echo git.short.sha = ${{ github.sha:7 }}
        echo github.event.pull_request_number = ${{ github.event.pull_request_number }}
