name: Testing Github Actions Things.

on:
  pull_request:
    branches: [main]

jobs:
  get-things:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set outputs
      id: vars
      run: |
        echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
        echo "::set-output name=port::3${{ github.event.pull_request.number }}"
    - name: Check outputs
      run: |
        echo ${{ steps.vars.outputs.sha_short }}
        echo ${{ steps.vars.outputs.port }}
